
### This file for Visual Studio Code Extension: REST Client
### Comfortable to use for making HTTP requests

### Cluster Health API
GET /_cluster/health?pretty
Host: localhost:9200
### Cluster Health API
GET /_cluster/health?pretty
Host: localhost:9201


###
GET /_nodes/stats?pretty
Host: localhost:9200
###
GET /_nodes/stats?pretty
Host: localhost:9201



### Cat Shards API
GET /_cat/shards?pretty
Host: localhost:9200
### Cat Shards API
GET /_cat/shards?pretty
Host: localhost:9201

### Count API
GET /filebeat-7.10.0-2024.04.03-000001/_count?pretty
Host: localhost:9200
### Count API
GET /filebeat-7.10.0-2024.04.03-000001/_count?pretty
Host: localhost:9201

### Count API
GET /logstash-2024.04.03/_count?pretty
Host: localhost:9200
### Count API
GET /logstash-2024.04.03/_count?pretty
Host: localhost:9201


###
GET /filebeat-7.10.0-2024.04.03-000001/_search?pretty
Host: localhost:9200

